
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.customql;

import java_cup.runtime.*;
import com.customql.ast.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CustomParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CustomParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CustomParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CustomParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\004\000\002\002\010\000\002\003" +
    "\005\000\002\003\003\000\002\004\005\000\002\004\003" +
    "\000\002\005\005\000\002\006\003\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\006\003\000\002\007\003\000\002\007\003\000\002\010" +
    "\006\000\002\010\002\000\002\011\003\000\002\011\003" +
    "\000\002\011\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\004\004\004\001\002\000\004\023\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\005\010\001\002\000\004\023\012\001\002\000" +
    "\010\007\033\010\032\014\ufff1\001\002\000\016\015\023" +
    "\016\022\017\020\020\021\021\024\022\025\001\002\000" +
    "\012\006\015\007\ufffe\010\ufffe\014\ufffe\001\002\000\012" +
    "\006\ufffc\007\ufffc\010\ufffc\014\ufffc\001\002\000\004\023" +
    "\012\001\002\000\012\006\ufffd\007\ufffd\010\ufffd\014\ufffd" +
    "\001\002\000\006\024\026\025\030\001\002\000\006\024" +
    "\ufff8\025\ufff8\001\002\000\006\024\ufff7\025\ufff7\001\002" +
    "\000\006\024\ufff9\025\ufff9\001\002\000\006\024\ufffa\025" +
    "\ufffa\001\002\000\006\024\ufff6\025\ufff6\001\002\000\006" +
    "\024\ufff5\025\ufff5\001\002\000\012\006\ufff4\007\ufff4\010" +
    "\ufff4\014\ufff4\001\002\000\012\006\ufffb\007\ufffb\010\ufffb" +
    "\014\ufffb\001\002\000\012\006\ufff3\007\ufff3\010\ufff3\014" +
    "\ufff3\001\002\000\004\014\042\001\002\000\004\011\035" +
    "\001\002\000\004\023\012\001\002\000\012\006\015\007" +
    "\uffff\010\uffff\014\uffff\001\002\000\004\023\036\001\002" +
    "\000\010\012\037\013\040\014\uffee\001\002\000\004\014" +
    "\ufff0\001\002\000\004\014\uffef\001\002\000\004\014\ufff2" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\003\010\004\012\005\013\001\001\000\004\010\030\001" +
    "\001\000\004\006\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\015\001\001\000\002\001\001\000" +
    "\004\007\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\033\005\013\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\040\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CustomParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CustomParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CustomParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException("Syntax error at line " + (cur_token.left + 1) + ", column " + (cur_token.right + 1));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CustomParser$actions {
  private final CustomParser parser;

  /** Constructor */
  CUP$CustomParser$actions(CustomParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CustomParser$do_action_part00000000(
    int                        CUP$CustomParser$act_num,
    java_cup.runtime.lr_parser CUP$CustomParser$parser,
    java.util.Stack            CUP$CustomParser$stack,
    int                        CUP$CustomParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CustomParser$result;

      /* select the action based on the action number */
      switch (CUP$CustomParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= query EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).right;
		QueryNode start_val = (QueryNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).value;
		RESULT = start_val;
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CustomParser$parser.done_parsing();
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // query ::= GET IDENTIFIER WHERE expresion_logica criterio_orden SEMI 
            {
              QueryNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-4)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).right;
		AstNode expr = (AstNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).value;
		int sortleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).left;
		int sortright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).right;
		SortNode sort = (SortNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).value;
		 RESULT = new QueryNode(id, expr, sort); 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("query",0, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-5)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expresion_logica ::= expresion_logica OR termino_logico 
            {
              AstNode RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).right;
		AstNode left = (AstNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		AstNode right = (AstNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = new LogicalExpressionNode(left, right); 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("expresion_logica",1, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expresion_logica ::= termino_logico 
            {
              AstNode RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		AstNode term = (AstNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = term; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("expresion_logica",1, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // termino_logico ::= termino_logico AND condicion 
            {
              AstNode RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).right;
		AstNode left = (AstNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		ConditionNode right = (ConditionNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = new LogicalTermNode(left, right); 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("termino_logico",2, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // termino_logico ::= condicion 
            {
              AstNode RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int condright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		ConditionNode cond = (ConditionNode)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = cond; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("termino_logico",2, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // condicion ::= IDENTIFIER operador valor 
            {
              ConditionNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = new ConditionNode(id, op, val); 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("condicion",3, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-2)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // operador ::= GT 
            {
              String RESULT =null;
		 RESULT = ">"; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // operador ::= LT 
            {
              String RESULT =null;
		 RESULT = "<"; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // operador ::= EQ 
            {
              String RESULT =null;
		 RESULT = "="; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // operador ::= GTE 
            {
              String RESULT =null;
		 RESULT = ">="; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // operador ::= LTE 
            {
              String RESULT =null;
		 RESULT = "<="; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // operador ::= NEQ 
            {
              String RESULT =null;
		 RESULT = "!="; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("operador",4, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // valor ::= NUMBER_LITERAL 
            {
              String RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = num; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("valor",5, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // valor ::= STRING_LITERAL 
            {
              String RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = str; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("valor",5, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // criterio_orden ::= SORT BY IDENTIFIER direccion 
            {
              SortNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-1)).value;
		int dirleft = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).left;
		int dirright = ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()).right;
		String dir = (String)((java_cup.runtime.Symbol) CUP$CustomParser$stack.peek()).value;
		 RESULT = new SortNode(id, dir); 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("criterio_orden",6, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.elementAt(CUP$CustomParser$top-3)), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // criterio_orden ::= 
            {
              SortNode RESULT =null;
		 RESULT = null; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("criterio_orden",6, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // direccion ::= ASC 
            {
              String RESULT =null;
		 RESULT = "ASC"; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("direccion",7, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // direccion ::= DESC 
            {
              String RESULT =null;
		 RESULT = "DESC"; 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("direccion",7, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // direccion ::= 
            {
              String RESULT =null;
		 RESULT = "ASC"; /* Default direction if missing, or null. Let's say null */ 
              CUP$CustomParser$result = parser.getSymbolFactory().newSymbol("direccion",7, ((java_cup.runtime.Symbol)CUP$CustomParser$stack.peek()), RESULT);
            }
          return CUP$CustomParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CustomParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CustomParser$do_action(
    int                        CUP$CustomParser$act_num,
    java_cup.runtime.lr_parser CUP$CustomParser$parser,
    java.util.Stack            CUP$CustomParser$stack,
    int                        CUP$CustomParser$top)
    throws java.lang.Exception
    {
              return CUP$CustomParser$do_action_part00000000(
                               CUP$CustomParser$act_num,
                               CUP$CustomParser$parser,
                               CUP$CustomParser$stack,
                               CUP$CustomParser$top);
    }
}

}
