
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.customql;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int WHERE = 3;
  public static final int AND = 4;
  public static final int LT = 12;
  public static final int DESC = 9;
  public static final int OR = 5;
  public static final int LTE = 15;
  public static final int SEMI = 10;
  public static final int SORT = 6;
  public static final int IDENTIFIER = 17;
  public static final int GT = 11;
  public static final int GTE = 14;
  public static final int STRING_LITERAL = 19;
  public static final int EOF = 0;
  public static final int BY = 7;
  public static final int NUMBER_LITERAL = 18;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int ASC = 8;
  public static final int NEQ = 16;
  public static final int GET = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GET",
  "WHERE",
  "AND",
  "OR",
  "SORT",
  "BY",
  "ASC",
  "DESC",
  "SEMI",
  "GT",
  "LT",
  "EQ",
  "GTE",
  "LTE",
  "NEQ",
  "IDENTIFIER",
  "NUMBER_LITERAL",
  "STRING_LITERAL"
  };
}

